### ISSUE TITLE
Problem of update. 

### ISSUE THREAD

**Issue by yuriyaowangyi** [uclnlp/stat-nlp-book#13]
Dear developer, 

I meet a problem of update, could you helps me figure it out. basically  i am presently a student of MSc Web science and Big data. I have attached the error message. 
Thank you so much 

yaowangyideMacBook-Pro:stat-nlp-book yaowangyi$  docker run -v $PWD:/home/jovyan/work riedelcastro/stat-nlp-book git pull
error: The following untracked working tree files would be overwritten by merge:
    data/ohhla/dev/www.ohhla.com/YFA_common.html
    data/ohhla/dev/www.ohhla.com/anonymous/b_rhymes/backonmy/decision.brm.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/beatnuts/massacre/slam_pit.btn.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/big_sean/detroit/common.bsn.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/big_sean/hallfame/switchup.bsn.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/blackstr/blackstr/respire.blk.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/brnubian/found/maybeone.brn.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/be.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/chi_city.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/corner.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/faithful.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/foodlive.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/go.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/its_your.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/love_is.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/r_people.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/testify.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/be/they_say.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/aquarius.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/between.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/close2me.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/electric.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/gotright.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/heaven.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/hustle.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/iammusic.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/new_wave.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/sl_power.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/circus/star_69.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/a_penny.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/blows_to.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/breaker.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/by_pound.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/charms.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/heidihoe.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/justnick.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/pitchin.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/puppy.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/takeitez.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/tricks.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dollar/twoscoop.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/believer.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/blue_sky.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/celebr8.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/cloth.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/dreamer.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/g_dreams.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/gd_remix.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/gold.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/lovinlst.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/pops_be.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/raw_howu.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/sweet.cms.txt.html
    data/ohhla/dev/www.ohhla.com/anonymous/common/dreamer/thebermx.cms.txt.html
    data/
Aborting
Updating 8993d56..c52edc8

**Comment by riedelcastro** [comment]
As I added the data to the repository, you need to first delete your data before it can be pulled. Do

``` bash
rm -rf data/ohhla
```

in your `stat-nlp-book` directory and then try again.

**Comment by yuriyaowangyi** [comment]
Thanks a lot.
