### ISSUE TITLE
Unable to sample from interpolated N-gram models.

### ISSUE THREAD

**Issue by Usefulmaths** [uclnlp/stat-nlp-book#23]
When trying to sample from an interpolated N-gram model, there is an error saying that the probabilities do not sum to one. This is despite the fact that the normalisation tests sum to 1 and the model gives a valid perplexity. Here's a simple model that demonstrates this issue.

![image](https://user-images.githubusercontent.com/8921102/31851063-40753e52-b656-11e7-9f4b-532e48eb33e7.png)

**Comment by riedelcastro** [comment]
Thanks! This might be due to numpy forcing strict normalisation constraints on the input to `random.choice`. But just to be sure, could also try to call the sampler with a single token initial history? I am actually not sure about the behaviour of the language model classes when they are not given a long enough history.

**Comment by Usefulmaths** [comment]
I tried calling the sampler with a single token, but it's still giving the same error. I inserted a print statement just before `random.choice` to see the sum of `probs` -- this evaluates to `~1.0712`, which is contradicting the normalisation tests.

Perhaps this is something to do with OOVAware? I've just tested this with the interpolated bigram model without OOVAware, and even though it doesn't pass the normalisation tests and it gives an infinite perplexity, it allows sampling.

**Comment by riedelcastro** [comment]
Ah, got it! The `OOVAware` model did still have the `oov` symbol in its vocabulary, and that's why the sum over `lm.vocab` didn't normalise. The assignment check still passes because it sums over the correct vocab. This is fixed in the current `master` branch, so git pull should help.
